name: CI

on:
  push:
  pull_request:

jobs:
  artifact-check:
    runs-on: windows-latest
      steps:
        -name: Checkout
        uses: actions/checkout@v4 

        -name: Run Artifact Check
        uses: scripts\check_artifact.cmd